In [1]:
!pip list

Package                            Version
---------------------------------- ---------------
absl-py                            2.1.0
adagio                             0.2.6
aiobotocore                        2.5.0
aiofiles                           22.1.0
aiohttp                            3.8.5
aioitertools                       0.7.1
aiosignal                          1.2.0
aiosqlite                          0.18.0
alabaster                          0.7.12
alembic                            1.8.1
anaconda-anon-usage                0.4.2
anaconda-catalogs                  0.2.0
anaconda-client                    1.12.1
anaconda-cloud-auth                0.1.3
anaconda-navigator                 2.5.0
anaconda-project                   0.11.1
annotated-types                    0.7.0
ansi2html                          1.9.2
antlr4-python3-runtime             4.11.1
anyascii                           0.3.2
anyio                              4.8.0
aplr                               10.8

In [16]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score, accuracy_score

import warnings
warnings.filterwarnings('ignore')

In [8]:
# load a dataset
iris = datasets.load_iris()

In [9]:
X = iris.data

In [10]:
y = iris.target

In [12]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [13]:
y[0]

np.int64(0)

In [14]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
# dataset split for training and testing purpose
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [17]:
# model instanatiation and model fitting
model = DecisionTreeClassifier(min_samples_split=100)
model.fit(X_train, y_train)

DecisionTreeClassifier(min_samples_split=100)

In [18]:
# prediction
y_pred = model.predict(X_test)
y_pred

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0])

In [19]:
# original values
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [28]:
y_pred

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0])

In [24]:
# size of the datasets
len(X), len(X_train), len(X_test)

(150, 120, 30)

In [25]:
# show the accuracy
accuracy = accuracy_score(y_test, y_pred)
print("accuracy", accuracy)

accuracy 0.6333333333333333


In [27]:
# show the f1score
f1score = f1_score(y_test, y_pred, average='macro')
print("f1_score", f1score)

f1_score 0.5402298850574713


In [31]:
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix, classification_report

In [30]:
confusion_matrix(y_test, y_pred)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0, 11,  0]])

In [ ]:
        0    1   2
array([[10,  0,  0],  0
       [ 0,  9,  0],  1
       [ 0, 11,  0]]) 2

In [34]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.45      1.00      0.62         9
           2       0.00      0.00      0.00        11

    accuracy                           0.63        30
   macro avg       0.48      0.67      0.54        30
weighted avg       0.47      0.63      0.52        30



In [44]:
print('prec:',10/10, 9/20, 0/0.0001)
print('recal:',10/10, 9/9, 0/11, 19/30)


prec: 1.0 0.45 0.0
recal: 1.0 1.0 0.0 0.6333333333333333


In [46]:
import mlflow

In [47]:
# http://127.0.0.1:5000

In [56]:
exp.experiment_id

'766651384492982543'

In [57]:
exp.name

'demo1'

In [49]:
mlflow.set_tracking_uri("http://127.0.0.1:5000")

In [55]:
exp = mlflow.set_experiment("demo1")

2025/02/15 09:59:40 INFO mlflow.tracking.fluent: Experiment with name 'demo1' does not exist. Creating a new experiment.


In [58]:
with mlflow.start_run(experiment_id = exp.experiment_id, run_name='myrun1'):
    mlflow.log_params({
        "min_samples_split": model.min_samples_split
    })
    
    mlflow.log_metric("accuracy",accuracy)
    mlflow.log_metric("f1score",f1score)
    
    mlflow.sklearn.log_model(model,"mymodel")
    
    print("accuracy", accuracy)
    print("f1_score", f1score)

2025/02/15 10:00:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.


accuracy 0.6333333333333333
f1_score 0.5402298850574713
🏃 View run myrun1 at: http://127.0.0.1:5000/#/experiments/766651384492982543/runs/a7a3bb9db0c046239de7a5aee9a382b3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/766651384492982543


In [59]:
mlflow.set_tracking_uri("http://127.0.0.1:5000")
exp = mlflow.set_experiment("demo1")

model = DecisionTreeClassifier(min_samples_split=20)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
f1score = f1_score(y_test, y_pred, average='macro')


with mlflow.start_run(experiment_id = exp.experiment_id, run_name='myrun2'):
    mlflow.log_params({
        "min_samples_split": model.min_samples_split
        
    })
    
    mlflow.log_metric("accuracy",accuracy)
    mlflow.log_metric("f1score",f1score)
    
    mlflow.sklearn.log_model(model,"mymodel")
    
    print("accuracy", accuracy)
    print("f1_score", f1score)

2025/02/15 10:10:29 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.


accuracy 1.0
f1_score 1.0
🏃 View run myrun2 at: http://127.0.0.1:5000/#/experiments/766651384492982543/runs/77b2788e4a724d8c8f35db79fdd9cefb
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/766651384492982543


In [ ]:
http://35.154.177.116:5000/

In [60]:
mlflow.set_tracking_uri("http://35.154.177.116:5000")
exp = mlflow.set_experiment("demo1")

model = DecisionTreeClassifier(min_samples_split=20)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
f1score = f1_score(y_test, y_pred, average='macro')


with mlflow.start_run(experiment_id = exp.experiment_id, run_name='zia-myrun1'):
    mlflow.log_params({
        "min_samples_split": model.min_samples_split
        
    })
    
    mlflow.log_metric("accuracy",accuracy)
    mlflow.log_metric("f1score",f1score)
    
    mlflow.sklearn.log_model(model,"mymodel")
    
    print("accuracy", accuracy)
    print("f1_score", f1score)

2025/02/15 10:41:29 INFO mlflow.tracking.fluent: Experiment with name 'demo1' does not exist. Creating a new experiment.
2025/02/15 10:41:51 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.


accuracy 1.0
f1_score 1.0
🏃 View run zia-myrun1 at: http://35.154.177.116:5000/#/experiments/247939155920337096/runs/7b6030b72a8f4a46a7753da4943dd8c4
🧪 View experiment at: http://35.154.177.116:5000/#/experiments/247939155920337096


In [61]:
mlflow.set_tracking_uri("http://35.154.177.116:5000")
exp = mlflow.set_experiment("demo1")

model = DecisionTreeClassifier(min_samples_split=120)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
f1score = f1_score(y_test, y_pred, average='macro')


with mlflow.start_run(experiment_id = exp.experiment_id, run_name='zia-myrun2'):
    mlflow.log_params({
        "min_samples_split": model.min_samples_split
        
    })
    
    mlflow.log_metric("accuracy",accuracy)
    mlflow.log_metric("f1score",f1score)
    
    mlflow.sklearn.log_model(model,"mymodel")
    
    print("accuracy", accuracy)
    print("f1_score", f1score)

2025/02/15 10:59:32 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.


accuracy 0.6333333333333333
f1_score 0.5402298850574713
🏃 View run zia-myrun2 at: http://35.154.177.116:5000/#/experiments/247939155920337096/runs/ca6218c3e8f84ce8b66626949cc4ef69
🧪 View experiment at: http://35.154.177.116:5000/#/experiments/247939155920337096


In [ ]:
# virtual server

In [ ]:
#import mlflow
# set the virutual server and access the model
mlflow.set_tracking_uri("http://35.154.177.116:5000")
logged_model = 'runs:/b5cb6933a97a4a0fb841897d050a69fa/mymodel'

# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

# Predict on a Pandas DataFrame.
#import pandas as pd
#loaded_model.predict(pd.DataFrame(data))
new_pred = loaded_model.predict(X_test)

new_acc = accurecy_score(y_test, new_pred)
print("accuracy", accuracy)

In [ ]:
# local server

In [64]:
mlflow.set_tracking_uri("http://127.0.0.1:5000")
logged_model = 'runs:/a7a3bb9db0c046239de7a5aee9a382b3/mymodel'

# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

# Predict on a Pandas DataFrame.
#import pandas as pd
#loaded_model.predict(pd.DataFrame(data))
new_pred = loaded_model.predict(X_test)

new_acc = accuracy_score(y_test, new_pred)
print("accuracy", accuracy)

accuracy 0.6333333333333333
