## Numpy Array Slicing

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8])

In [ ]:
#Slicing Sytax = Arrname[start:stop:step] till stop-1th index is fetch
print(a[0:5])

[1 2 3 4 5]


In [ ]:
print(a[:5])

[1 2 3 4 5]


In [ ]:
print(a[3:])

[4 5 6 7 8]


In [ ]:
print(a)

[1 2 3 4 5 6 7 8]


In [ ]:
print(a[:])

[1 2 3 4 5 6 7 8]


In [ ]:
#Print elements at Even indices
print(a[3:6])

[4 5 6]


In [ ]:
#Print elements at Even indices
print(a[0::2])

[1 3 5 7]


### Concept of array slicing is the same for lists as well

In [ ]:
lst = [1,2,3,4,5]
lst[1:5]

[2, 3, 4, 5]

## -ve indexing

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8])

In [ ]:
a[-1]

8

In [ ]:
a[-1::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
a[-1:-6:-1]

array([8, 7, 6, 5, 4])

In [ ]:
arr[start:stop:step=1]

In [ ]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [ ]:
arr.shape

(2, 4)

In [ ]:
arr[0:2,1:3]

array([[2, 3],
       [2, 3]])

## Datatypes

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

In [ ]:
print(arr.dtype)

int64


`i` - Integer - Sign-Bit 2^31 2^30 --------- 2^1 -  32-bit - 1 <br>
`b` - Bool <br>
`u` - Unsigned Integer <br>
`f` - float <br>
`c` - complex float <br>
`m` - time delta <br>
`M` - datetime <br>
`O` - Object <br>
`S` - strings <br>

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6], dtype = 'S')

In [ ]:
print(arr.dtype)

|S1


In [ ]:
print(arr)

[b'1' b'2' b'3' b'4' b'5' b'6']


In [ ]:
import numpy as np

arr = np.array(['a',2,3,4,5,6], dtype = 'i')

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
import numpy as np

arr = np.array([1,0,0,1,5,6])

In [ ]:
print(arr.dtype)

int64


In [ ]:
import numpy as np

arr = np.array([1,0,0,1,5,6])

newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False False  True  True  True]
bool


In [ ]:
a = 5
if a:
  print(True)

True


In [ ]:
a = None
if a:
  print(True)

## Reshape operation

In [ ]:
import numpy as np
range_vals = np.array(range(0,16,1))

In [ ]:
range_vals.shape

(16,)

In [ ]:
4x4
2x4x2

In [ ]:
matrix = range_vals.reshape(4,4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
matrix.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## flatten(), ravel()

## Iterating through an array

In [ ]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
for i in matrix:
  print(i)
  for j in i:
    print(j)

[0 1 2 3]
0
1
2
3
[4 5 6 7]
4
5
6
7
[ 8  9 10 11]
8
9
10
11
[12 13 14 15]
12
13
14
15


## Creating an Identity Matrix

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.eye(1)

array([[1.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Dot product

In [ ]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
I4 = np.eye(4)

In [ ]:
I4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
a = np.dot(I4,matrix)
b = np.dot(matrix,I4)

In [ ]:
assert a.shape == b.shape

In [ ]:
assert a == b

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
b

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [ ]:
print(b.dtype)

float64


In [ ]:
a

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [ ]:
np.alltrue(a==b)

True

In [ ]:
np.allclose(a,b)

True

In [ ]:
np.allclose?



```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-68-46f3032e8f4c> in <cell line: 1>()
----> 1 assert a == b

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```



Using all() as the error suggested

In [ ]:
assert (a == b).all()

In [ ]:
assert 4==5

AssertionError: 

## 5 more mins please - Be back by 10:30

In [ ]:
arr = np.array([[1,2,3,4],[1,2,3,4]])
arr.shape
arr[0:2,1:3]

array([[2, 3],
       [2, 3]])

In [ ]:
arr = np.array([[1,2,3,4],[1,2,3,4]])
arr.shape
arr[0:2]

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

## Numpy operations

In [ ]:
range(0,1,0.1) #Range generates intergers not float

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
matA = np.arange(0.1,1,0.1).reshape(3,3)

In [ ]:
matB = matA*3

In [ ]:
matC = matB*3

In [ ]:
matC

array([[0.9, 1.8, 2.7],
       [3.6, 4.5, 5.4],
       [6.3, 7.2, 8.1]])

In [ ]:
matB

array([[0.3, 0.6, 0.9],
       [1.2, 1.5, 1.8],
       [2.1, 2.4, 2.7]])

In [ ]:
matA

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])

In [ ]:
np.add(matA,matB)

array([[0.4, 0.8, 1.2],
       [1.6, 2. , 2.4],
       [2.8, 3.2, 3.6]])

In [ ]:
np.subtract(matA,matB)

array([[-0.2, -0.4, -0.6],
       [-0.8, -1. , -1.2],
       [-1.4, -1.6, -1.8]])

In [ ]:
np.multiply(matA,matB)

array([[0.03, 0.12, 0.27],
       [0.48, 0.75, 1.08],
       [1.47, 1.92, 2.43]])

## Technically , the matrices cannot be divided . But if you remember the basic concept of division of two fractions , then one fraction remains the same but the other fraction gets inverted and multiplied to the former fraction for performing the division

In [ ]:
A.(some Matrix) = I

In [ ]:
np.divide(matA,matB) #Element wise division of two elements of matrices

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

In [ ]:
arr = np.array([1,2,3,4,5,6],dtype = 'float64')

In [ ]:
np.reciprocal(arr)

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667])

In [ ]:
mat1 = np.array([1,2,3,4,5,6]).reshape(3,2)

In [ ]:
mat1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
mat2 = mat1*3

In [ ]:
mat1.shape

(3, 2)

In [ ]:
mat2.shape

(3, 2)

In [ ]:
mat1.T

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
mat2

array([[ 3,  6],
       [ 9, 12],
       [15, 18]])

In [ ]:
np.dot(mat1.T,mat2) #@ - short hand for dot product

array([[105, 132],
       [132, 168]])

In [ ]:
mat1.T @ mat2 #Inner product - (2,3)(3,2)
mat1 @ mat2.T #outer product - (3,2)(2,3)

In [ ]:
arr1 = np.array([5,10,15])
arr2 = np.array([2,5,3])

In [ ]:
np.mod(arr1,arr2)

array([1, 0, 0])

In [ ]:
np.remainder(arr1,arr2)

array([1, 0, 0])

In [ ]:
np.sin?

In [ ]:
 A = [[1,2],[3,4]]

In [ ]:
np.dot(A,np.linalg.inv(A))

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [ ]:
#Instead of converting to boolen using astype, can we use like below:
arr = np.array([1,0,0,1,5,6], dtype='bool')

In [ ]:
arr

array([ True, False, False,  True,  True,  True])

In [ ]:
#Instead of converting to boolen using astype, can we use like below:
arr = np.array([1,0,0,1,5,6], dtype='B')

In [4]:
!pip install pysqlite3
import sqlite3
import pandas as pd

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 kB 656.5 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pysqlite3: filename=pysqlite3-0.5.3-cp310-cp310-linux_x86_64.whl size=151107 sha256=832838b5af7c2f38a89b9e85c517bbcd7fe8e48e7621a2da5bac48b5f05b04bf
  Stored in directory: /root/.cache/pip/wheels/6d/5b/04/3e6115d6b90cd4d63a55c4d13685fe8117bb87d5997a215e71
Successfully built pysqlite3


In [5]:
csv_file_path = 'https://raw.githubusercontent.com/nursnaaz/FutureDataScienceLegends/main/Python/Pandas_Basics_1/IMDB-Movie-Data.csv'
db_file_path = 'MDB-Movie-Data.db'
New_table_name = 'IMDB_Movie_Data'
df = pd.read_csv(csv_file_path)
conn = sqlite3.connect(db_file_path)
df.to_sql(New_table_name, conn, if_exists='replace')
dbfile_df=pd.read_sql_query("select * from IMDB_Movie_Data",conn)
dbfile_df

index  Rank                    Title                     Genre  \
0        0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1        1     2               Prometheus  Adventure,Mystery,Sci-Fi   
2        2     3                    Split           Horror,Thriller   
3        3     4                     Sing   Animation,Comedy,Family   
4        4     5            Suicide Squad  Action,Adventure,Fantasy   
..     ...   ...                      ...                       ...   
995    995   996     Secret in Their Eyes       Crime,Drama,Mystery   
996    996   997          Hostel: Part II                    Horror   
997    997   998   Step Up 2: The Streets       Drama,Music,Romance   
998    998   999             Search Party          Adventure,Comedy   
999    999  1000               Nine Lives     Comedy,Family,Fantasy   

                                           Description              Director  \
0    A group of intergalactic criminals are forced ...            James Gunn   
1    Following clues to the origin of mankind, a te...          Ridley Scott   
2    Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3    In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4    A secret government agency recruits some of th...            David Ayer   
..                                                 ...                   ...   
995  A tight-knit team of rising investigators, alo...             Billy Ray   
996  Three American college students studying abroa...              Eli Roth   
997  Romantic sparks occur between two dance studen...            Jon M. Chu   
998  A pair of friends embark on a mission to reuni...        Scot Armstrong   
999  A stuffy businessman finds himself trapped ins...      Barry Sonnenfeld   

                                                Actors  Year  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014   
1    Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012   
2    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016   
3    Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016   
4    Will Smith, Jared Leto, Margot Robbie, Viola D...  2016   
..                                                 ...   ...   
995  Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...  2015   
996  Lauren German, Heather Matarazzo, Bijou Philli...  2007   
997  Robert Hoffman, Briana Evigan, Cassie Ventura,...  2008   
998  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014   
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016   

     Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore  
0                  121     8.1  757074              333.13       76.0  
1                  124     7.0  485820              126.46       65.0  
2                  117     7.3  157606              138.12       62.0  
3                  108     7.2   60545              270.32       59.0  
4                  123     6.2  393727              325.02       40.0  
..                 ...     ...     ...                 ...        ...  
995                111     6.2   27585                 NaN       45.0  
996                 94     5.5   73152               17.54       46.0  
997                 98     6.2   70699               58.01       50.0  
998                 93     5.6    4881                 NaN       22.0  
999                 87     5.3   12435               19.64       11.0  

[1000 rows x 13 columns]