## Numpy - Numerical Python

Python library - Arrays - 2005

- Lists served the purpose of arrays
- 50x faster than traditional lists
- very frequently used in Data Science
- Mathematical foothold - Maths

Numpy stores one continuos place in memory
- Speed Efficiency
- Memory Usage - data is store contiguosly in memory, which enhances performance by efficient access.
- Mathematical operations are easy
- N-Dimensional Data handling

In [2]:
!pip install numpy

In [1]:
import numpy

In [4]:
import numpy as np #Allocating an alias for the package numpy

In [15]:
a = np.array((1,2,3,4,5,6,7)) #Here no information of second dimension

In [16]:
a.shape

(7,)

In [22]:
a = np.array([[1],
              [2],
              [3],
              [4],
              [5],
              [6],
              [7]]) #I am explicitly passing information of dimensions

In [23]:
a.shape

(7, 1)

In [27]:
a = np.array([[1,2],
              [2,2],
              [3,2],
              [4,2],
              [5,2],
              [6,2],
              [7,2]])

In [29]:
a.shape

(7, 2)

In [28]:
a.T #Transpose

array([[1, 2, 3, 4, 5, 6, 7],
       [2, 2, 2, 2, 2, 2, 2]])

In [30]:
a.T.shape

(2, 7)

## Indexing

In [31]:
a = np.array((1,2,3,4,5,6,7)) #Here no information of second dimension
print(a[0])

1


In [39]:
a = np.array([[1,2],
              [2,2],
              [3,2],
              [4,2],
              [5,2],
              [6,2],
              [7,2]])

In [40]:
a[0][0]

1

In [41]:
a[0,0]

1

In [43]:
a = np.array([[[1,2],
               [2,2]],
              [[3,2],
               [4,2]],
              [[5,2],
               [6,2]]])

In [44]:
a.shape

(3, 2, 2)

In [45]:
a

array([[[1, 2],
        [2, 2]],

       [[3, 2],
        [4, 2]],

       [[5, 2],
        [6, 2]]])

In [49]:
a[0][1][1]

2

In [60]:
a[0,1,1]

2

In [55]:
a.shape

(3, 2, 2)

In [73]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a.shape

(2, 2, 2)

In [76]:
a[0] #By default numpy arrays are queried row by row to change it I am changing to column

array([[1, 2],
       [3, 4]])

In [77]:
a[0].T #By default numpy arrays are queried row by row to change it I am changing to column

array([[1, 3],
       [2, 4]])

In [ ]:
#if A = A.T what is it called?

In [69]:
a=np.array(
    [[
      [1,2,3,4,5] #Shape 2x1x5
    ],
    [
        [2,3,4,5,6]
    ]])

In [70]:
a.shape

(2, 1, 5)

In [71]:
sh=np.array ([[[1,"g"],[2,"b"]],[[3,"c"],[4,"d"]],[[5,"e"],[6,"f"]]])

In [92]:
a1 = np.array([
    [
        [[1,2],[3,3],[5,6]]
    ],


    [
        [[9,8],[7,6],[0,3]]
    ]
              ])

In [104]:
a1.shape

(2, 1, 3, 2)

In [98]:
a1

array([[[[1, 2],
         [3, 3],
         [5, 6]]],


       [[[9, 8],
         [7, 6],
         [0, 3]]]])

In [100]:
a1[0]

array([[[1, 2],
        [3, 3],
        [5, 6]]])

In [97]:
a1[0].shape

(1, 3, 2)

In [105]:
a1.T.shape

(2, 3, 1, 2)

In [103]:
a1[0].T

array([[[1],
        [3],
        [5]],

       [[2],
        [3],
        [6]]])

In [102]:
a1[0].T.shape

(2, 3, 1)

In [106]:
type(a)

numpy.ndarray

In [ ]:
AA-1 = I

In [ ]:
5 x 1/5 = 1
A . 1/A = I

In [109]:
def somefunction():
  """
  Some Docstring
  """