In [2]:
house_price_model_lr

NameError: name 'house_price_model_lr' is not defined

In [4]:
import joblib

In [6]:
house_price_model_lr = joblib.load('house_price_lr_model.pkl')

In [8]:
house_price_model_lr

LinearRegression()

In [10]:
house_price_model_lr.predict([[1,2,3,0,3]])

/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([729804.40188364])

In [12]:
house_price_model_lr.coef_

array([ 7.47730161e+04,  3.16932330e+04,  2.37117472e+04,  5.63573846e+01,
       -2.03867742e+04])

In [14]:
house_price_model_lr.intercept_

581670.0006187578

In [20]:
house_price_model_lr.predict([[1,2,3,0,3]])

/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([729804.40188364])

In [24]:
import numpy as np

In [28]:
house_price_model_lr.predict([[1,2,np.NaN,0,3]])

/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values