In [2]:
import numpy as np

In [6]:
X = np.array([[1,1],
          [1,2],
           [1,3]])

In [8]:
X

array([[1, 1],
       [1, 2],
       [1, 3]])

In [14]:
X.shape

(3, 2)

In [10]:
y = np.array([2,3,5])

In [12]:
y

array([2, 3, 5])

In [16]:
y.shape

(3,)

In [18]:
#((X^T).X)^-1.((X^T).y)

In [20]:
X.T

array([[1, 1, 1],
       [1, 2, 3]])

In [22]:
X.T @ X

array([[ 3,  6],
       [ 6, 14]])

In [24]:
np.linalg.inv(X.T @ X)

array([[ 2.33333333, -1.        ],
       [-1.        ,  0.5       ]])

In [30]:
(X.T @ y)

array([10, 23])

In [26]:
np.linalg.inv(X.T @ X) @ (X.T @ y)

array([0.33333333, 1.5       ])

In [ ]:
# b = 0.33
# m = 1.5

In [40]:
no_of_scoop = 15

In [42]:
price_of_icecream = 1.5*(no_of_scoop)+0.33

In [44]:
price_of_icecream

22.83