In [56]:
import numpy as np

In [82]:
X = np.array([[1, 10, 5, 2],
              [1, 20, 2, 1],
              [1, 5,  1, 1]])

In [84]:
X

array([[ 1, 10,  5,  2],
       [ 1, 20,  2,  1],
       [ 1,  5,  1,  1]])

In [86]:
X.shape

(3, 4)

In [88]:
y = np.array([5,2,1])

In [90]:
y

array([5, 2, 1])

In [92]:
y.shape

(3,)

In [94]:
#((X^T).X)^-1.((X^T).y)

In [96]:
X.T

array([[ 1,  1,  1],
       [10, 20,  5],
       [ 5,  2,  1],
       [ 2,  1,  1]])

In [98]:
X.T @ X

array([[  3,  35,   8,   4],
       [ 35, 525,  95,  45],
       [  8,  95,  30,  13],
       [  4,  45,  13,   6]])

In [100]:
np.linalg.inv(X.T @ X)

array([[ 2.23211625e+16, -4.96025833e+14,  7.44038750e+15,
        -2.72814208e+16],
       [-4.96025833e+14,  1.10227963e+13, -1.65341944e+14,
         6.06253796e+14],
       [ 7.44038750e+15, -1.65341944e+14,  2.48012917e+15,
        -9.09380694e+15],
       [-2.72814208e+16,  6.06253796e+14, -9.09380694e+15,
         3.33439588e+16]])

In [102]:
(X.T @ y)

array([ 8, 95, 30, 13])

In [104]:
np.linalg.inv(X.T @ X) @ (X.T @ y)

array([-128.,    8.,   32.,  -64.])

In [106]:
# b = -128
# bill = 8
# no_of_customer = 32
# no_of_server = -64

In [ ]:
tip_amount = -128 + 8*Bill_amount + 
             32*no_of_customers - 64*no_hotel_servers

In [ ]:
y = house_price
x1 = square_feet

y = 6000 + 5.5*square_feet

In [ ]:
y = target data

x1, x2, x3, ...

x1, x3

In [ ]:
[